### ISSUE TITLE
Drone won't fly

### ISSUE THREAD

**Issue by hbzhang** [JD-ETH/AirSimNeurIPS#1]
Never see the drone fly:
![drone](https://user-images.githubusercontent.com/205781/77350064-58826180-6d12-11ea-8e92-215da7c0e516.png)

Runtime output

/home/hbzhang/anaconda3/envs/py37/lib/python3.7/site-packages/quaternion/numba_wrapper.py:20: UserWarning:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Could not import from numba, which means that some
parts of this code may run MUCH more slowly.  You
may wish to install numba.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  warnings.warn(warning_text)
Connected!
Connected!
Connected!
Controller planning for first goal.
('Planning finished for: ', 0)
Race Started.
Started odometry callback thread
Advancing, Constraint at  1  speed  None  checks:  (0.405, 8.0)  goal at  [-5.31999779e+01 -1.65400009e+02  1.57890835e+01  1.00000000e+00
 -3.87750980e-06  0.00000000e+00]
Controller needs replan due to finished goal.
Started Control thread
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/hbzhang/anaconda3/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/hbzhang/anaconda3/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "daniel.py", line 349, in apply_control
    input = self.mpc_control.getInput(drone_state)
  File "/home/hbzhang/opt/race/AirSimNeurIPS/Daniel/control.py", line 136, in getInput
    X, U = self.getFullMpcOutput(state)
  File "/home/hbzhang/opt/race/AirSimNeurIPS/Daniel/control.py", line 158, in getFullMpcOutput
    np.transpose(np.tile(self.Q,self.horizon)), self.Qf, 0)
ValueError: Expecting double matrix 1x4 for x0

Planning finished
Deviating from path: cur min:  3.270086270123526
Shortest reference at:  [-6.76222300e+01 -1.65742261e+02  2.05628951e+01 -5.37410072e-01
 -6.29929323e-01  5.12515020e-01 -2.27393528e-01  3.49715995e+00
  7.47523120e+00  2.75829935e+01  5.60843636e+00  8.50086349e-01
 -8.33360600e-01 -5.69350357e-02]
Now at at:  <Vector3r> {   'x_val': -68.05735778808594,
    'y_val': -166.64027404785156,
    'z_val': 17.448781967163086}
Controller needs replan due to deviation, enter stablizing mode.
Planning finished.
Deviating from path: cur min:  2.0030785706223586
Shortest reference at:  [-6.80399974e+01 -1.66492098e+02  1.89346437e+01  2.18921756e-01
 -8.20261498e-01  5.08268610e-01 -1.44593773e-01  2.76207593e-01
  2.87705108e+00  2.98159579e+01  7.43465724e+00  5.50776434e-01
 -4.81496129e-01 -1.72444656e-02]
Now at at:  <Vector3r> {   'x_val': -67.86662292480469,
    'y_val': -167.6032257080078,
    'z_val': 17.277036666870117}
Controller needs replan due to deviation, enter stablizing mode.
Planning finished.
Controller needs replan due to reference too short.
Planning finished.

**Comment by JD-ETH** [comment]
you probably didn't build the MPC code. It needs to be generated from ACADO. 
Update this script and change to corresponding paths. 
`mpc_control/codegen.sh`

**Comment by hbzhang** [comment]
I have run the code. The code has error. 

I used another source. The MPC controller looks installed correctly.  

Import acado works. But when I run the test code for MPC (test.py). It complains the following

ValyuError: expecting double matrix 1X4 for x0

**Comment by hbzhang** [comment]
I have run the code. The code has error.

I used another source. The MPC controller looks installed correctly.

Import acado works. But when I run the test code for MPC (test.py). It
complains the following

ValyuError: expecting double matrix 1X4 for x0

**Comment by hbzhang** [comment]
Traceback (most recent call last):
  File
"/Users/zhangh/opt/classes/2020/drone/AirSimNeurIPS/mpc_control/quadrotor_mpc_codegen/test.py",
line 46, in <module>
    X, U = acado.mpc(0, 1, x0,X,U,Y,yN, np.transpose(np.tile(Q,T)), Qf, 0)
ValueError: Expecting double matrix 1x4 for x0

When I run your test.py

import numpy as np
import acado
import time

# Time horizon
T=40
# Number of differential state variables.
NX=10
# Number of control inputs.
NU=4
# Number of input reference.
NY=14
# Number of final stage cost.
NYN = 10
# Initial state.
x0 = np.zeros((1,NX))
x0[0,3] = 1.0
# Unknowns.
X = np.zeros((T+1, NX))
U = np.zeros((T,NU))
# Reference hover state with input. Move to x equals 2.
xref = np.zeros((1,NX))
xref[0,2] = -1.0
xref[0,3] = 1.0
Y=np.zeros((T,NY))
for i in range(0,T):
  Y[i,2]=-1
  Y[i,3]=1
  Y[i,10]=1

# Final value.
yN=np.zeros((1,NYN))
yN[0,2] = -1
yN[0,3] = 1
Q = np.diag([100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 10.0,
10.0, 10.0, 1.0, 1.0, 1.0, 1.0])
Qf = Q[:10, :10]


counter = 0
# x0 [1, NX]
# X [N+1, NX]
# U [N, NU]
# Y [N, NY]
# yN [1, NYN]
for i in range(0,1000):
  X, U = acado.mpc(0, 1, x0,X,U,Y,yN, np.transpose(np.tile(Q,T)), Qf, 0)
  if counter % 1000 == 0:
    print(counter)
  counter = counter + 1

print('U', U)
print('X', X)

**Comment by JD-ETH** [comment]
you need to adapt the pathing in the bash file so that the python binding builds correctly.

**Comment by JD-ETH** [comment]
Could you run the `python Daniel/test.py` file? Not sure the `test.py` you tried is still up to date. 
Where did you generate the acado code? The source file I use is modifed from the original version.

**Comment by JD-ETH** [comment]
I believe I have missed some information about codegen, please take a look at the Installation guideline section on the project page again.

**Comment by hbzhang** [comment]
cd ../../ACADOtoolkit/build
make
cd ../../ACADOtoolkit/examples/code_generation/mpc_mhe/

!!! This file does not exist!!!
./code_generation_quadrotor_model_thrustrates

**!!! This file does not exist!!!**
cd ~/competition/KiteRunner/mpc_control

**rm -rf quadrotor_mpc_codegen**
mv ../../ACADOtoolkit/examples/code_generation/mpc_mhe/quadrotor_mpc_codegen ./


cp -r ../../rpg_mpc/externals/qpoases quadrotor_mpc_codegen/


cp python/* quadrotor_mpc_codegen/
cd quadrotor_mpc_codegen
python3 setup.py build install --force
cd ..

**Comment by JD-ETH** [comment]
`code_generation_quadrotor_model_thrustrates` is a binary that should be produced by acado after the build

**Comment by JD-ETH** [comment]
modify `cd ~/competition/KiteRunner/mpc_control` to `cd ../../../AirSimNeuRIPS/mpc_control`

**Comment by JD-ETH** [comment]
if `code_generation_quadrotor_model_thrustrates ` is not there that means you didn't copy the file to that folder

**Comment by hbzhang** [comment]
Where is the code_generation_quadrotor_model_thrustrates?

I do not find that there is such file...

**Comment by hbzhang** [comment]
Can you provide all the files (ACADOtoolkit and rpg_mpc) into one folder so that I can easily compile and do pip install?

**Comment by JD-ETH** [comment]
No the source file. the `code_gen` is a binary that you have to build on your machine. 
Please read the instruction carefully on the README. look at this:
`
mv mpc_control/quadrotor_model_thrustrates.cpp ../../ACADOtoolkit/examples/code_generation/mpc_mhe/`

What do you need to do pip install for ?

**Comment by JD-ETH** [comment]
If i have time or if there is more interest I will consider adding submodules

**Comment by hbzhang** [comment]
mv ../../ACADOtoolkit/examples/code_generation/mpc_mhe/quadrotor_mpc_codegen ./

**there is no /quadrotor_mpc_codegen folder under mpc_mhe folder!!**

**Comment by JD-ETH** [comment]
You need to build first. 
```
cd ../../ACADOtoolkit/build
make
``` 
In the script.

**Comment by JD-ETH** [comment]
If you don't build there is no generated code. Please instead of asking for help immediately, take some time to think about what's happening..

**Comment by hbzhang** [comment]
Thanks. problem solved setup.py can be executed and install successfully for ACADO python interface. Thanks, I am new to this framework. I guess there are many small details to explore.

But the problem still persists, complaining about the matrix dimension problem.  Do you get the same complain for the following test.py python code for MPC?


Traceback (most recent call last):
  File
"/Users/zhangh/opt/classes/2020/drone/AirSimNeurIPS/mpc_control/quadrotor_mpc_codegen/test.py",
line 46, in <module>
    X, U = acado.mpc(0, 1, x0,X,U,Y,yN, np.transpose(np.tile(Q,T)), Qf, 0)
ValueError: Expecting double matrix 1x4 for x0

When I run your test.py

import numpy as np
import acado
import time

# Time horizon
T=40
# Number of differential state variables.
NX=10
# Number of control inputs.
NU=4
# Number of input reference.
NY=14
# Number of final stage cost.
NYN = 10
# Initial state.
x0 = np.zeros((1,NX))
x0[0,3] = 1.0
# Unknowns.
X = np.zeros((T+1, NX))
U = np.zeros((T,NU))
# Reference hover state with input. Move to x equals 2.
xref = np.zeros((1,NX))
xref[0,2] = -1.0
xref[0,3] = 1.0
Y=np.zeros((T,NY))
for i in range(0,T):
  Y[i,2]=-1
  Y[i,3]=1
  Y[i,10]=1

# Final value.
yN=np.zeros((1,NYN))
yN[0,2] = -1
yN[0,3] = 1
Q = np.diag([100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 10.0,
10.0, 10.0, 1.0, 1.0, 1.0, 1.0])
Qf = Q[:10, :10]


counter = 0
# x0 [1, NX]
# X [N+1, NX]
# U [N, NU]
# Y [N, NY]
# yN [1, NYN]
for i in range(0,1000):
  X, U = acado.mpc(0, 1, x0,X,U,Y,yN, np.transpose(np.tile(Q,T)), Qf, 0)
  if counter % 1000 == 0:
    print(counter)
  counter = counter + 1

print('U', U)
print('X', X)

**Comment by JD-ETH** [comment]
this test file is outdated. please try the `Daniel/test.py` instead and check if a visualization appears.

**Comment by hbzhang** [comment]
Thanks. The test file under Daniel works. I have another issue kind of related to this issue, but I want to keep it separate.  I will file another issue.

**Comment by JD-ETH** [comment]
Will then consider this closed.
