### ISSUE TITLE
NED-ENU conventions

### ISSUE THREAD

**Issue by AlessandroSaviolo** [JD-ETH/AirSimNeurIPS#3]
Hi!

In control.py you invert the sign of pitch and yaw. Is it for converting bodyrates from ENU to NED convention?
If so, why don't you do the conversion from NED to ENU when you pass the input data (i.e., odometry and trajectory) to the MPC?

Thanks in advance!

**Comment by JD-ETH** [comment]
Yeah I remember the convention to be different and it took a while to get it to work. I think the reason I kept it was because I already had the working MPC code and didn't want to change there. Doing it inside MPC will obviously work as well.

**Comment by AlessandroSaviolo** [comment]
Thanks for the quick reply! So you pass in input to the MPC the same odometry returned by Airsim without transforming it?

**Comment by JD-ETH** [comment]
Yes it seems so inside control.py. I believe the control convention might be different from the frame convention tho, but I don't exactly remember, you might want to check the docs.

**Comment by AlessandroSaviolo** [comment]
Finally I found the right combination of conventions. Thanks for the help!
